# Generated by Django 2.1 on 2018-09-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='characters.CharacterTypes'),
        ),
    ]
